# Generated by Django 5.0.2 on 2024-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangjobs',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hydjobs',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='punejobs',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
